name: LAB787
favicon: null
layout_spectrum: 0.8991097891703248
typography_spectrum: 0.14077656040899456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19216385600157082
  lightness: 0.574106409214437
  saturation: 0.01599225657992065
  rhythmicContrast: 0.47948825918138027
purpose: []
